### ISSUE TITLE
Module does not create order

### ISSUE THREAD

**Issue by yogiben** [bitpay/prestashop-plugin#10]
We're running a freshly installed prestashop and have just installed and configured the bitpay module.

When making an order, the bitcoins are accepted and arrive in our bitpay account, but no order is made in the CMS system.

Are we missing something?

**Comment by lfelipeqn** [comment]
I'm having this same problem. After the payment is received, no order is created.

**Comment by pieterpoorthuis** [comment]
@lfelipeqn Which version of PrestaShop are you running?
Did you install the proper release from https://github.com/bitpay/prestashop-plugin/releases ?

Can you provide of a sample order id or bitcoin transaction id?

**Comment by lfelipeqn** [comment]
@pieterpoorthuis we are using prestashop version 1.6.1.11 and we have installed the module for version 1.6 from repository.

The transaction details here:
[https://insight.bitpay.com/tx/373ad99aa7d1878336febd7f2bf8350948f6e523ed76778a6cb59615de362c6f]
Bitpay transaction: RDHzHrVFraKxH2gMDP43qV
In prestashop: A cart 19895 was created, but no order was associated to that cart.
Bitpay is using cart number from prestashop as invoice id.
