### ISSUE TITLE
PrestaShop v1.6.0.9: Some Formating Issues

### ISSUE THREAD

**Issue by Master0ne** [bitpay/prestashop-plugin#17]
Using the default template, the BitPay box is not properly formated on the OPC (quick-order):

![opc](https://cloud.githubusercontent.com/assets/8912853/4402475/f70e538a-4497-11e4-92cc-4b36219a0401.png)

The problem seems to be that it does not properly get included encapsulated in a row. This is how it should look like:

![row](https://cloud.githubusercontent.com/assets/8912853/4402477/ff377bae-4497-11e4-9cc6-c6a813564716.png)

And this is how it looks for the bitpay module:

![bitpay_no_row](https://cloud.githubusercontent.com/assets/8912853/4402486/0cb9d222-4498-11e4-92c8-9cfa165ab58e.png)

As you can see, the two divs are missing, and just the paragraph getting inserted, causing the bitpay box stretch uncontrolled horizontally.

I have already tried to find the issue in the code by comparing the files in the bitpay module folder with the ones in the bankwire module folder, but I have no idea what I'm looking for.

Another problem: Although the bitpay module is installed and enabled properly, it does not show up on the Modules>>Payment page as active payment module:

![modules_payment_page](https://cloud.githubusercontent.com/assets/8912853/4402492/140275e8-4498-11e4-9e25-2e04a88310e6.png)

**Comment by ionux** [comment]
This issue is fixed in the latest official Release.  It has been re-packaged correctly and will be going forward, as well.
