### ISSUE TITLE
Update module to Prestashop 1.6

### ISSUE THREAD

**Issue by fiharleh** [bitpay/prestashop-plugin#24]
Hi,

This module seems to be calling all order functions for Previous Prestashop 1.5?
Could you please update the hole module so it works with prestashop 1.6?

For example you are calling on bitpay.php -->
$options['redirectURL'] = (Configuration::get('PS_SSL_ENABLED') ? 'https://' : 'http://').htmlspecialchars($_SERVER['HTTP_HOST'], ENT_COMPAT, 'UTF-8').__PS_BASE_URI__.'order-confirmation.php?id_cart='.$cart->id.'&id_module='.$this->id.'&id_order='.$this->currentOrder;

And while looking /site/order-confirmation.php on Prestashop 1.6 there isnt files anymore?
Prestashop 1.5 files are saying messages like this one:

/**
 * This file will be removed in 1.6
 * You have to use index.php?controller=page_name instead of this page
 *
 * @deprecated 1.5.0
 */

**Comment by ionux** [comment]
Working for latest version.

**Comment by brohemath** [comment]
I am having same problem, I have loaded the module in 1.4 and 1.5 without issue but when loading into 1.6 it never shows up in the module selection on the backend. 
I have tried everything, manually putting them in their respective folders, trying to add it from "add module" tab and nothing seems to work.
