### ISSUE TITLE
You have not placed any orders.

### ISSUE THREAD

**Issue by justinfielder** [bitpay/prestashop-plugin#25]
Installed the latest plugin on a clean 1.6.0.9 PrestaShop and all I get after the invoice has been paid when it returns to the store is "You have not placed any orders".

The return link is http://mystore.###########.com/shoplive/index.php?controller=order-confirmation&id_cart=1&id_module=70&id_order=

Which would tend to suggest you aren't getting the order ID correct?

**Comment by justinfielder** [comment]
Hi Guys,

Sorry for the delay in testing this (something called Christmas got in the way) but just to let you know it works fine.

I've 'hacked' in a '15% discount for paying in BTC' by a simple change in bitpay.php
      $options['price']            = $total * 0.85;

and the reciprocal in ipn.php
		$myprice = (float) $decoded['price'];
		error_log("returnprice = ".$myprice); //log for debugging purposes
		$myprice = $myprice / 0.85;
		error_log("returnprice upscaled = ".$myprice); //log for debugging purposes
		$decoded['price'] = $myprice;

It's not perfect because for small values you sometimes get rounding errors which means that the return doesn't match exactly, so the final thing I've done is changed the payment_error order status in PrestaShop to be "Payment awaiting full verification" which means that the customer thinks that it is just awaiting verification in the blockchain and our order agents can check it's just that an then flip it to Payment Accepted.

It would be nice if you are in a coding mood to add in an option for the discount and enable the API to sort it out so that the discount is done entirely within BitPay and therefore the correct price is always returned, but we can live with it.

Once we are live with the new shop I'll let you know where it is.

Much coolness and thanks for all the fixes.

J

**Comment by java-guy** [comment]
@philosodad or anyone else: I'm not a developer and neither do I understand github. It would be great if you could still help me. As far as I understand this conversation I'm having the same problem as mentioned above.

I've downloaded the zip file which is offered here and installed the plugin on a test environment (risk setting=medium). Then I've created an order. After clicking on "check out" I see the page with the payment instructions and QR code but in the backend I don't see that an order was created. Of course also no email is sent out. After 15 min. the payment instructions page shows "this order has expired".

I would have expected the same behaviour as with payment via bank wire: after clicking on "check out" an order is created, payment instructions are displayed + sent to the client via email.
Did I make some mistake while installing? Or is it somehow possible to change this behaviour?

**Comment by justinfielder** [comment]
You actually have to pay the invoice at the QR code stage.....!

Create a test product for something small value wise, get your favourite wallet with some BTC in it, pay it and once you do BitPay will complete the transaction.

If you set BitPay to not settle the BTC into fiat then your Bitcoins will come back to you minus BitPay's fees.

J

Sent whilst mobile

**Comment by philosodad** [comment]
Quick note: we don't charge any fees, so you should get the Bitcoins back minus the Bitcoin networks transaction fees, which your wallet should show you.

**Comment by justinfielder** [comment]
I guessed he didn't understand bitcoin as he didn't know how to pay an invoice so complicating different types of transaction fees felt too much :)

**Comment by ionux** [comment]
@justinfielder @java-guy If you are still having this issue, feel free to reopen this thread.  Otherwise since there hasn't been any traffic on this for a month I'm assuming everything is copacetic.

**Comment by java-guy** [comment]
@ionux Well, since there's no way to make a test payment and since I don't have (and don't want to own) an own btc wallet I went live with the plugin untested. I'm now going to wait until someone either succeeds in making a purchase or complains. Neither happened so far...

**Comment by philosodad** [comment]
There is a way to make a test payment, and you can create a test wallet using test bitcoin. That's one of our steps in testing each plugin. Making a test payment does require modifying one of the files, if you are interested in doing so I can explain what to do.

**Comment by grejjn** [comment]
I installed the plugin bitpay-prestashop-1.5.0.zip in PrestaShop 1.6.0.14, PHP version 5.4.38. Payment goes through bitpay and was accepted but the store does not place any orders. Plugin is not compatible with the version of PrestaShop 1.6.0.14?

**Comment by philosodad** [comment]
@grejjn what security/speed level are you set at? High speed is broken, only medium and slow will work.

**Comment by grejjn** [comment]
@philosodad I know that high speed is not working. I set the plugin and the user's account BitPay transaction rate to "medium". Bitcoin Payment is accepted but the store does not place any orders. In the history of customer orders and PrestaShop admin panel is not listed orders. I also wrote for BitPay support and wait for answer.

**Comment by philosodad** [comment]
As far as I know, the bitpay plugin works with PrestaShop 1.6. I will have a look at this later this week and see if I can find anything. In them meantime it would be helpful to have as much information about your setup and any error logs you might have.

**Comment by grejjn** [comment]
I do not have at the store "https" and certainly this is the cause of the error. How to Install an SSL Certificate to write if it works. Thanks for your interest in the problem;)

**Comment by ionux** [comment]
You can create and install a self-signed certificate to test with but that's really outside the scope of what we help with here though, sorry.  There are many good tutorials for setting up a secure webserver out there if you search for the topic.  Probably better than I could explain anyway!  :)
