### ISSUE TITLE
Not working with EU Legal

### ISSUE THREAD

**Issue by Sykh** [bitpay/prestashop-plugin#31]
Hey there,
i am running a shop (1.6.0.13) in Germany so i have installed EU Legal
http://www.silbersaiten.de/page/prestashop/eu-legal.html
Downside - it removes bitpay from the available payment methods - any fix for that?

Thanks

**Comment by ionux** [comment]
Thanks for the report.  Do you have logs or error messages detailing any problems that are happening?

**Comment by Sykh** [comment]
I've googled a bit and it seems like eu-legal is delisting every "non eu" payment method, bitpay is listed at the "displayPayment" hook but i got another "displayPaymentEU" hook which is actually in use now.

Not sure if i have to add it in eu-legal or if i can modify that hook in bitpay...

This is the version i am using:
https://github.com/EU-Legal/modules-1.6.0.13

**Comment by ionux** [comment]
Ah, I see what you're saying.  I'm working on a patch now and will update you when we've tested it out.

**Comment by ionux** [comment]
Hey @Sykh , as I've been experimenting with some changes I have discovered that this will require a pretty significant update to our plugin and also a modification to the EU-Legal plugin.  I have to put this project on our to-do list for future development.  As soon as we can wrap up some existing projects, this one will be in the chute next.

**Comment by Sykh** [comment]
Too bad but thanks for the quick replies!
