### ISSUE TITLE
Error Message with Module version 1.5 and Prestashop 1.6.1.2

### ISSUE THREAD

**Issue by java-guy** [bitpay/prestashop-plugin#36]
- error messages are enabled in defines.inc 
- When opening any order in the backoffice (must not even be paid with bitpay), I get the following error message:
  Notice in line 355 of file /var/www/example-shop.com_stage/www/modules/bitpay/bitpay.php
  [8] Undefined offset: 0

**Comment by kleetus** [comment]
Is this issue just affecting version 1.6.1.2?
