### ISSUE TITLE
Error: no data returned from API server!

### ISSUE THREAD

**Issue by alphaonex86** [bitpay/prestashop-plugin#40]
Hello,

I have this error: Error: no data returned from API server!
Include with the plugins updated.

Cheers,

**Comment by kleetus** [comment]
Hello:

Can you kindly reply with the versions of:
1. BitPay prestashop-plugin 
2. Prestashop
3. PHP
4. the operating system

thanks

**Comment by alphaonex86** [comment]
1) seam have not bean updated: bitpay v0.4 - by BitPay
2) 1.6.0.9
3) PHP 5.6.19-pl0-gentoo
4) Gentoo linux
