### ISSUE TITLE
Problems with Bitpay install in Prestashop 1.6

### ISSUE THREAD

**Issue by Gabedal** [bitpay/prestashop-plugin#47]
Hello,
I have my e-commerce with Prestashop 1.6.1.4. I follow the installation instructions: Download the 1.6 prestashop module,  install it, put the API key...

When I do the check out, the option "Pay with Bitpay" appear, but when I choose this option I you press the pay button.... only en empty window appear with the text: "Payment confirmation" , and nothing more happens!!! 
Any idea about what can I do?

**Comment by pieterpoorthuis** [comment]
Did you follow the instructions at https://bitpay.com/integrations/prestashop ?

Please make sure your BitPay merchant account is fully configured (email verified, settlement information entered, company information entered.).

You can easily test whether your account is is setup correctly by making a test payment using the 'quick checkout for web' link on https://bitpay.com/dashboard/merchant/edit-mobile-checkout
 
The minimum invoice price is $1. If you try to create an invoice below, you'll get a blank page.
