### ISSUE TITLE
PS 1.7.2.2 - Installation fail

### ISSUE THREAD

**Issue by winnerLX** [bitpay/prestashop-plugin#48]
On PS 1.7.2.2 a BitPay plugin failed to install

**Comment by pieterpoorthuis** [comment]
Can you describe in more detail what happens? 

Did you follow the installation instructions from https://bitpay.com/integrations/prestashop?
Did you install the latest BitPay plugin for PS 1.7: https://github.com/bitpay/prestashop-plugin/releases/download/v1.7.0/bitpay_prestashop_v1.7.zip

**Comment by lorzele** [comment]
![bitpay](https://user-images.githubusercontent.com/24669180/31407651-e18f420a-ae05-11e7-85a8-248c5f7fc5ce.jpg)

**Comment by lorzele** [comment]
![bitpay1](https://user-images.githubusercontent.com/24669180/31407760-5c453fd6-ae06-11e7-9370-0bec8592b5d3.jpg)

**Comment by winnerLX** [comment]
![bitpay3](https://user-images.githubusercontent.com/24669180/31414759-d2927636-ae1f-11e7-83ec-19198a803220.jpg)

**Comment by pieterpoorthuis** [comment]
I tried to replicate, but on my Prestashop 1.7.2.2 the installation works just fine.

If you have time, let's setup a skype call. So I we can work together to find out what goes wrong. You can email me at pieter at bitpay dot com.

**Comment by NommoPL** [comment]
Hey,
I do have same issue on PrestaShop 1.7.2.4.
It says that "Module BitPay must be installed first".

Any ideas? :)

**Comment by pieterpoorthuis** [comment]
Fixed in v1.7.1
