### ISSUE TITLE
Cannot install 1.7.2

### ISSUE THREAD

**Issue by Texxer** [bitpay/prestashop-plugin#51]
![chrome_2018-08-22_19-01-24](https://user-images.githubusercontent.com/22458550/44478405-de718e80-a63d-11e8-92e2-671cec07191e.png)

Any help appreciated. Currently running 1.6

**Comment by pieterpoorthuis** [comment]
It looks like you downloaded the source code, instead of the compiled module.

Can you try again by downloading & installing this file: https://github.com/bitpay/prestashop-plugin/releases/download/v1.7.1/bitpay_prestashop_v1.7.1.zip

**Comment by Texxer** [comment]
Thank you for version 1.7.1 pieter.

I anticipated to run with the latest.

Solved for now.
